# Generated by Django 5.0.6 on 2024-07-11 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
