# Generated by Django 5.0.6 on 2024-07-09 08:57

import CMSAPP.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('type_medicine', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('storage_requirements', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opid', models.CharField(default=CMSAPP.models.generate_opid, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(null=True)),
                ('time_slot', models.CharField(choices=[('09:00-09:30', '09:00-09:30 AM'), ('09:30-10:00', '09:30-10:00 AM'), ('10:00-10:30', '10:00-10:30 AM')], max_length=11, null=True)),
                ('token', models.CharField(default=CMSAPP.models.generate_token, editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='CMSAPP.doctors')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_appointments', to='CMSAPP.specialization')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='CMSAPP.patient_details')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.CharField(max_length=30, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('diagnosis', models.CharField(max_length=100, null=True)),
                ('doctor_note', models.CharField(max_length=100, null=True)),
                ('next_visit', models.DateField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSAPP.bookappointment')),
            ],
        ),
        migrations.CreateModel(
            name='MedPrescribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.IntegerField(default=0)),
                ('noon', models.IntegerField(default=0)),
                ('night', models.IntegerField(default=0)),
                ('frequency', models.IntegerField(default=0)),
                ('date_of_prescribition', models.DateField()),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSAPP.diagnosis')),
                ('med_list', models.ManyToManyField(to='CMSAPP.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_name', to='CMSAPP.bookappointment')),
                ('medicines', models.ManyToManyField(related_name='medicine_name', to='CMSAPP.medprescribed')),
                ('opid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_opid', to='CMSAPP.bookappointment')),
                ('quantities', models.ManyToManyField(related_name='pharmacist_quantities', to='CMSAPP.medprescribed')),
                ('unit_rates', models.ManyToManyField(related_name='pharmacist_unit_rates', to='CMSAPP.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSAPP.supplier'),
        ),
    ]
