# Generated by Django 5.0.6 on 2024-07-11 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedPrescribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.IntegerField(default=0)),
                ('noon', models.IntegerField(default=0)),
                ('night', models.IntegerField(default=0)),
                ('frequency', models.IntegerField(default=0)),
                ('date_of_prescribition', models.DateField()),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSAPP.diagnosis')),
                ('med_list', models.ManyToManyField(to='CMSAPP.medicine')),
            ],
        ),
    ]
