# Generated by Django 5.0.6 on 2024-07-11 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSAPP', '0002_counter_report_supplier_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200, unique=True)),
                ('low_value', models.IntegerField(blank=True, null=True)),
                ('high_value', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient_details',
            name='emergency_contact',
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='appointment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='time_slot',
            field=models.CharField(choices=[('09:00-09:30', '09:00-09:30 AM'), ('09:30-10:00', '09:30-10:00 AM'), ('10:00-10:30', '10:00-10:30 AM')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.CharField(max_length=30, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('diagnosis', models.CharField(max_length=100, null=True)),
                ('doctor_note', models.CharField(max_length=100, null=True)),
                ('next_visit', models.DateField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSAPP.bookappointment')),
            ],
        ),
        migrations.CreateModel(
            name='TestPrescribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_prescribition', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('lab_tests', models.ManyToManyField(to='CMSAPP.newtest')),
                ('labtests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSAPP.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='LiveTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_value', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('prescribed_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='CMSAPP.testprescribed')),
            ],
        ),
    ]
