# Generated by Django 5.0.6 on 2024-07-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSAPP', '0004_alter_user_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctors',
            name='fees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gender',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=models.DateField(), max_length=128),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
