# Generated by Django 5.0.6 on 2024-07-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSAPP', '0005_remove_user_department_remove_doctors_dept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='clinics', max_length=128),
        ),
    ]
