# Generated by Django 5.0.6 on 2024-07-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSAPP', '0006_alter_user_contact_number_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
